spring:
  profiles.active: local
  application:
     name: web

security:
  basic:
    enabled: false

logging:
  level:
    io.pivotal.springtrader: 'INFO'

---
spring:
  profiles: local

  jpa:
     hibernate:
        ddl-auto: create-drop
server:
  port: 8080

quotes:
  url: http://localhost:8086

accounts:
  url: http://localhost:8082

portfolios:
  url: http://localhost:8081

---
spring:
  profiles: cloud
  jpa:
     hibernate:
        ddl-auto: update

quotes:
  url: http://quotes-xxxx-yyyy.cfapps.io

accounts:
  url: http://accounts-xxxx-yyyy.cfapps.io
  
portfolios:
  url: http://portfolios-xxxx-yyyy.cfapps.io


